services:
  - type: web
    name: image-processing-service # Replace with your actual service name
    env: python
    buildCommand: |
      apt-get update && \
      apt-get install -y pkg-config libgtk-3-dev libwebkit2gtk-4.0-dev tesseract-ocr libleptonica-dev && \
      pip install -r requirements.txt
    startCommand: python app.py # Replace with the command to start your application
